#
# Conf reload triggers so changes to the modular input and settings stanza
# don't require a splunkd restart.
#

[shclustering]
conf_replication_include.airspace_watch = true
conf_replication_include.airspace_watch_settings = true
